Added Test Jobs

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -58,8 +58,34 @@ jobs:
         id: 'setup-monorepo'
         with:
           install: '${{ matrix.projectName }}...'
-          build: '${{ matrix.projectName }}'
       - name: 'Lint'
+        run: 'pnpm --filter="${{ matrix.projectName }}" ${{ matrix.command }}'
+  project-test-jobs:
+    name: 'Test - ${{ matrix.projectName }} - ${{ matrix.name }}'
+    runs-on: 'ubuntu-20.04'
+    needs: 'project-jobs'
+    if: ${{ needs.project-jobs.outputs.test-jobs != '[]' }}
+    strategy:
+      fail-fast: false
+      matrix:
+        include: ${{ fromJSON( needs.project-jobs.outputs.test-jobs ) }}
+    steps:
+      - uses: 'actions/checkout@v3'
+        name: 'Checkout'
+        with:
+          fetch-depth: 0
+      - uses: './.github/actions/setup-woocommerce-monorepo'
+        name: 'Setup Monorepo'
+        id: 'setup-monorepo'
+        with:
+          install: '${{ matrix.projectName }}...'
+          build: '${{ matrix.projectName }}'
+      - name: 'Prepare Test Environment'
+        id: 'prepare-test-environment'
+        if: ${{ matrix.testEnv }}
+        env: ${{ matrix.testEnv.envVars }}
+        run: 'pnpm --filter="${{ matrix.projectName }}" ${{ matrix.testEnv.start }}'
+      - name: 'Test'
         run: 'pnpm --filter="${{ matrix.projectName }}" ${{ matrix.command }}'
   evaluate-project-jobs:
     # In order to add a required status check we need a consistent job that we can grab onto.
@@ -71,7 +97,8 @@ jobs:
     runs-on: 'ubuntu-20.04'
     needs: [ 
       'project-jobs',
-      'project-lint-jobs'
+      'project-lint-jobs',
+      'project-test-jobs'
     ]
     if: ${{ always() }}
     steps:
@@ -85,6 +112,11 @@ jobs:
           result="${{ needs.project-lint-jobs.result }}"
           if [[ $result != "success" && $result != "skipped" ]]; then
             echo "One or more lint jobs have failed."
+            exit 1
+          fi
+          result="${{ needs.project-test-jobs.result }}"
+          if [[ $result != "success" && $result != "skipped" ]]; then
+            echo "One or more test jobs have failed."
             exit 1
           fi
           echo "All jobs have completed successfully."
