CI: test changes.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -154,26 +154,21 @@ jobs:
   project-test-jobs:
     name: '${{ matrix.name }}'
     runs-on: ubuntu-latest
-    needs: [ 'project-jobs', 'validate-changelog' ]
-    # Complex conditions part:
-    # -- all test types will run for PRs with code changes or on other events
-    # -- performance tests in draft PRs will not run until it semi-ready (failing changelog validation as indication of WIP)
-    if: >
-      ${{
-          !cancelled() &&
-          needs.project-jobs.outputs.test-jobs != '[]' &&
-          ( github.event_name != 'pull_request' || needs.identify-jobs-to-run.outputs.needs-code-validation == 'true' ) && 
-          ( github.event_name != 'pull_request' || github.event.pull_request.draft == false || matrix.testType != 'performance' || needs.validate-changelog.result != 'failure' ) 
-      }}
+    needs: 'project-jobs'
+    if: ${{ !cancelled() && ( github.event_name != 'pull_request' || needs.identify-jobs-to-run.outputs.needs-code-validation == 'true' ) && needs.project-jobs.outputs.test-jobs != '[]' }}
     env: ${{ matrix.testEnv.envVars }}
-    # environment: exposes matrix.testType for using in if-statement above
-    environment: ${{ matrix.testType }}
     strategy:
       fail-fast: false
       max-parallel: 30
       matrix:
         include: ${{ fromJSON( needs.project-jobs.outputs.test-jobs ) }}
     steps:
+      - name: 'Terminate early performance jobs for WIP draft PRs'
+        if: ${{ github.event_name == 'pull_request' && github.event.pull_request.draft == true || matrix.testType == 'performance' || needs.validate-changelog.result == 'failure' }}
+        run: |
+          echo 'Aborting the job execution: failing changelog validation treated as WIP draft PR.'
+          exit 1
+
       - uses: 'actions/checkout@v4'
         name: 'Checkout'
 
