Old PR workflow to use composite actions

diff --git a/.github/workflows/pr-build-and-e2e-tests.yml b/.github/workflows/pr-build-and-e2e-tests.yml
--- a/.github/workflows/pr-build-and-e2e-tests.yml
+++ b/.github/workflows/pr-build-and-e2e-tests.yml
@@ -11,78 +11,11 @@ concurrency:
 
 permissions: {}
 
+env:
+    PR_NUMBER: ${{ github.event.pull_request.number }}
+    PR_TITLE: ${{ github.event.pull_request.title }}
+
 jobs:
-    e2e-tests-run:
-        if: ${{ github.event_name != 'pull_request' || github.event.pull_request.user.login != 'github-actions[bot]' }}
-        name: Runs E2E tests.
-        runs-on: ubuntu-20.04
-        permissions:
-            contents: read
-        env:
-            ALLURE_RESULTS_DIR: ${{ github.workspace }}/plugins/woocommerce/tests/e2e-pw/test-results/allure-results
-            ALLURE_REPORT_DIR: ${{ github.workspace }}/plugins/woocommerce/tests/e2e-pw/test-results/allure-report
-        outputs:
-            E2E_GRAND_TOTAL: ${{ steps.count_e2e_total.outputs.E2E_GRAND_TOTAL }}
-        steps:
-            - uses: actions/checkout@v3
-
-            - name: Setup WooCommerce Monorepo
-              uses: ./.github/actions/setup-woocommerce-monorepo
-
-            - name: Load docker images and start containers.
-              working-directory: plugins/woocommerce
-              env:
-                  ENABLE_HPOS: 0
-                  WP_ENV_PHP_VERSION: 7.4
-              run: pnpm run env:test
-
-            - name: Download and install Chromium browser.
-              working-directory: plugins/woocommerce
-              run: pnpm exec playwright install chromium
-
-            - name: Get total number of Playwright E2E tests to be run.
-              id: count_e2e_total
-              working-directory: plugins/woocommerce
-              run: |
-                  TOTAL_STR=$(pnpm exec playwright test --config=tests/e2e-pw/playwright.config.js --list | grep "Total:")
-                  NO_PREFIX=${TOTAL_STR#*"Total: "}
-                  COUNT=${NO_PREFIX%" tests in"*}
-                  echo "E2E_GRAND_TOTAL=$COUNT" >> $GITHUB_OUTPUT
-
-            - name: Run Playwright E2E tests.
-              timeout-minutes: 60
-              id: run_playwright_e2e_tests
-              env:
-                  USE_WP_ENV: 1
-                  E2E_MAX_FAILURES: 15
-                  FORCE_COLOR: 1
-              working-directory: plugins/woocommerce
-              run: pnpm exec playwright test --config=tests/e2e-pw/playwright.config.js
-
-            - name: Generate Playwright E2E Test report.
-              id: generate_e2e_report
-              if: |
-                  always() &&
-                  (
-                    steps.run_playwright_e2e_tests.conclusion != 'cancelled' ||
-                    steps.run_playwright_e2e_tests.conclusion != 'skipped' 
-                  )
-              working-directory: plugins/woocommerce
-              run: pnpm exec allure generate --clean ${{ env.ALLURE_RESULTS_DIR }} --output ${{ env.ALLURE_REPORT_DIR }}
-
-            - name: Archive Playwright E2E test report
-              if: |
-                  always() &&
-                  steps.generate_e2e_report.conclusion == 'success'
-              uses: actions/upload-artifact@v3
-              with:
-                  name: e2e-test-report---pr-${{ github.event.number }}
-                  path: |
-                      ${{ env.ALLURE_RESULTS_DIR }}
-                      ${{ env.ALLURE_REPORT_DIR }}
-                  if-no-files-found: ignore
-                  retention-days: 5
-
     api-tests-run:
         name: Runs API tests.
         if: github.event.pull_request.user.login != 'github-actions[bot]'
@@ -97,174 +30,203 @@ jobs:
 
             - name: Setup WooCommerce Monorepo
               uses: ./.github/actions/setup-woocommerce-monorepo
-
-            - name: Load docker images and start containers.
-              working-directory: plugins/woocommerce
-              env:
-                  ENABLE_HPOS: 0
-              run: pnpm env:test --filter=woocommerce
-
-            - name: Run Playwright API tests.
-              id: run_playwright_api_tests
-              working-directory: plugins/woocommerce
-              env:
-                  BASE_URL: http://localhost:8086
-                  USER_KEY: admin
-                  USER_SECRET: password
-              run: pnpm exec playwright test --config=tests/api-core-tests/playwright.config.js
-
-            - name: Generate Playwright API Test report.
-              id: generate_api_report
-              if: |
-                  always() &&
-                  (
-                    steps.run_playwright_api_tests.conclusion != 'cancelled' ||
-                    steps.run_playwright_api_tests.conclusion != 'skipped' 
-                  )
-              working-directory: plugins/woocommerce
-              run: pnpm exec allure generate --clean ${{ env.ALLURE_RESULTS_DIR }} --output ${{ env.ALLURE_REPORT_DIR }}
-            - name: Archive Playwright API test report
-              if: |
-                  always() &&
-                  steps.generate_api_report.conclusion == 'success'
-              uses: actions/upload-artifact@v3
               with:
-                  name: api-test-report---pr-${{ github.event.number }}
-                  path: |
-                      ${{ env.ALLURE_RESULTS_DIR }}
-                      ${{ env.ALLURE_REPORT_DIR }}
-                  if-no-files-found: ignore
-                  retention-days: 5
+                  build-filters: woocommerce
 
-    k6-tests-run:
-        name: Runs k6 Performance tests
-        if: github.event.pull_request.user.login != 'github-actions[bot]'
+            - name: Setup local test environment
+              uses: ./.github/actions/tests/setup-local-test-environment
+              with:
+                  test-type: api
+
+            - name: Run API tests
+              id: api-action
+              uses: ./.github/actions/tests/run-api-tests
+              with:
+                  report-title: API Test report for "${{ env.PR_TITLE }} (#${{ env.PR_NUMBER }})"
+                  tests: hello # mytodo remove
+
+            - name: Publish report
+              if: success() || ( failure() && steps.api-action.result == 'failure' )
+              uses: ./.github/actions/tests/reports/publish-report-pr
+              with:
+                  key-id: ${{ secrets.REPORTS_AWS_ACCESS_KEY_ID }}
+                  region: ${{ secrets.REPORTS_AWS_REGION }}
+                  access-key: ${{ secrets.REPORTS_AWS_SECRET_ACCESS_KEY }}
+                  reports-home: ${{ secrets.REPORTS_BUCKET }}
+                  test-type: api
+
+    e2e-tests-run:
+        name: Runs E2E tests.
+        needs: [api-tests-run]
         runs-on: ubuntu-20.04
         permissions:
             contents: read
+        env:
+            ALLURE_RESULTS_DIR: ${{ github.workspace }}/plugins/woocommerce/tests/e2e-pw/test-results/allure-results
+            ALLURE_REPORT_DIR: ${{ github.workspace }}/plugins/woocommerce/tests/e2e-pw/test-results/allure-report
+        outputs:
+            TOTAL: ${{ steps.e2e-action.outputs.total }}
         steps:
             - uses: actions/checkout@v3
 
             - name: Setup WooCommerce Monorepo
               uses: ./.github/actions/setup-woocommerce-monorepo
 
-            - name: Load docker images and start containers.
-              working-directory: plugins/woocommerce
+            - name: Setup local test environment
+              uses: ./.github/actions/tests/setup-local-test-environment
+              with:
+                  test-type: e2e
+
+            - name: Run E2E tests
+              id: e2e-action
+              timeout-minutes: 60
+              uses: ./.github/actions/tests/run-e2e-tests
               env:
-                  ENABLE_HPOS: 0
-              run: |
-                  pnpm env:dev --filter=woocommerce
-                  pnpm env:performance-init --filter=woocommerce
-
-            - name: Install k6
-              run: |
-                  curl https://github.com/grafana/k6/releases/download/v0.33.0/k6-v0.33.0-linux-amd64.tar.gz -L | tar xvz --strip-components 1
-
-            - name: Run k6 tests
-              run: |
-                  ./k6 run plugins/woocommerce/tests/performance/tests/gh-action-pr-requests.js
-
-    test-summary:
-        name: Post test results
-        if: |
-            always() && 
-            ! github.event.pull_request.head.repo.fork &&
-            github.event.pull_request.user.login != 'github-actions[bot]' &&
-            (
-              contains( needs.*.result, 'success' ) ||
-              contains( needs.*.result, 'failure' )
-            )
-        runs-on: ubuntu-20.04
-        needs: [api-tests-run, e2e-tests-run]
-        permissions:
-            contents: read
-            issues: write
-            pull-requests: write
-        env:
-            E2E_GRAND_TOTAL: ${{needs.e2e-tests-run.outputs.E2E_GRAND_TOTAL}}
-        steps:
-            - name: Create dirs
-              run: |
-                  mkdir -p repo
-                  mkdir -p artifacts/api 
-                  mkdir -p artifacts/e2e
-                  mkdir -p output
-
-            - name: Checkout code
-              uses: actions/checkout@v3
+                  E2E_MAX_FAILURES: 15
               with:
-                  path: repo
+                  report-title: E2E Test report for "${{ env.PR_TITLE }} (#${{ env.PR_NUMBER }})"
+                  tests: basic.spec.js # mytodo remove
 
-            - name: Download API test report artifact
-              uses: actions/download-artifact@v3
+            - name: Publish report
+              if: success() || ( failure() && steps.e2e-action.result == 'failure' )
+              uses: ./.github/actions/tests/reports/publish-report-pr
               with:
-                  name: api-test-report---pr-${{ github.event.number }}
-                  path: artifacts/api
+                  key-id: ${{ secrets.REPORTS_AWS_ACCESS_KEY_ID }}
+                  region: ${{ secrets.REPORTS_AWS_REGION }}
+                  access-key: ${{ secrets.REPORTS_AWS_SECRET_ACCESS_KEY }}
+                  reports-home: ${{ secrets.REPORTS_BUCKET }}
+                  test-type: e2e
 
-            - name: Download Playwright E2E test report artifact
-              uses: actions/download-artifact@v3
-              with:
-                  name: e2e-test-report---pr-${{ github.event.number }}
-                  path: artifacts/e2e
+    # mytodo refactor k6 tests
+    # k6-tests-run:
+    #     name: Runs k6 Performance tests
+    #     needs: [api-tests-run]
+    #     runs-on: ubuntu-20.04
+    #     permissions:
+    #         contents: read
+    #     steps:
+    #         - uses: actions/checkout@v3
 
-            - name: Prepare test summary
-              id: prepare-test-summary
-              uses: actions/github-script@v6
-              env:
-                  API_SUMMARY_PATH: ${{ github.workspace }}/artifacts/api/allure-report/widgets/summary.json
-                  E2E_PW_SUMMARY_PATH: ${{ github.workspace }}/artifacts/e2e/allure-report/widgets/summary.json
-                  PR_NUMBER: ${{ github.event.number }}
-                  SHA: ${{ github.event.pull_request.head.sha }}
-              with:
-                  result-encoding: string
-                  script: |
-                      const script = require( './repo/.github/workflows/scripts/prepare-test-summary.js' )
-                      return await script( { core } )
+    #         - name: Setup WooCommerce Monorepo
+    #           uses: ./.github/actions/setup-woocommerce-monorepo
 
-            - name: Find PR comment by github-actions[bot]
-              uses: peter-evans/find-comment@034abe94d3191f9c89d870519735beae326f2bdb
-              id: find-comment
-              with:
-                  issue-number: ${{ github.event.pull_request.number }}
-                  comment-author: 'github-actions[bot]'
-                  body-includes: Test Results Summary
+    #         - name: Load docker images and start containers.
+    #           working-directory: plugins/woocommerce
+    #           env:
+    #               ENABLE_HPOS: 0
+    #           run: |
+    #               pnpm env:dev --filter=woocommerce
+    #               pnpm env:performance-init --filter=woocommerce
 
-            - name: Create or update PR comment
-              uses: peter-evans/create-or-update-comment@67dcc547d311b736a8e6c5c236542148a47adc3d
-              with:
-                  comment-id: ${{ steps.find-comment.outputs.comment-id }}
-                  issue-number: ${{ github.event.pull_request.number }}
-                  body: ${{ steps.prepare-test-summary.outputs.result }}
-                  edit-mode: replace
+    #         - name: Install k6
+    #           run: |
+    #               curl https://github.com/grafana/k6/releases/download/v0.33.0/k6-v0.33.0-linux-amd64.tar.gz -L | tar xvz --strip-components 1
 
-    publish-test-reports:
-        name: Publish test reports
-        if: |
-            always() && 
-            ! github.event.pull_request.head.repo.fork &&
-            github.event.pull_request.user.login != 'github-actions[bot]' &&
-            (
-              contains( needs.*.result, 'success' ) ||
-              contains( needs.*.result, 'failure' )
-            )
-        runs-on: ubuntu-20.04
-        needs: [api-tests-run, e2e-tests-run, k6-tests-run]
-        env:
-            GITHUB_TOKEN: ${{ secrets.REPORTS_TOKEN }}
-            PR_NUMBER: ${{ github.event.number }}
-            RUN_ID: ${{ github.run_id }}
-            COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
-        steps:
-            - name: Publish test reports
-              env:
-                  API_ARTIFACT: api-test-report---pr-${{ github.event.number }}
-                  E2E_ARTIFACT: e2e-test-report---pr-${{ github.event.number }}
-              run: |
-                  gh workflow run publish-test-reports-pr.yml \
-                    -f run_id=$RUN_ID \
-                    -f api_artifact=$API_ARTIFACT \
-                    -f e2e_artifact=$E2E_ARTIFACT \
-                    -f pr_number=$PR_NUMBER \
-                    -f commit_sha=$COMMIT_SHA \
-                    -f s3_root=public \
-                    --repo woocommerce/woocommerce-test-reports
+    #         - name: Run k6 tests
+    #           run: |
+    #               ./k6 run plugins/woocommerce/tests/performance/tests/gh-action-pr-requests.js
+# mytodo add links to HPOS tests
+# test-summary:
+#     name: Post test results
+#     if: |
+#         always() &&
+#         ! github.event.pull_request.head.repo.fork &&
+#         github.event.pull_request.user.login != 'github-actions[bot]' &&
+#         (
+#           contains( needs.*.result, 'success' ) ||
+#           contains( needs.*.result, 'failure' )
+#         )
+#     runs-on: ubuntu-20.04
+#     needs: [api-tests-run, e2e-tests-run]
+#     permissions:
+#         contents: read
+#         issues: write
+#         pull-requests: write
+#     env:
+#         E2E_GRAND_TOTAL: ${{needs.e2e-tests-run.outputs.E2E_GRAND_TOTAL}}
+#     steps:
+#         - name: Create dirs
+#           run: |
+#               mkdir -p repo
+#               mkdir -p artifacts/api
+#               mkdir -p artifacts/e2e
+#               mkdir -p output
+
+#         - name: Checkout code
+#           uses: actions/checkout@v3
+#           with:
+#               path: repo
+
+#         - name: Download API test report artifact
+#           uses: actions/download-artifact@v3
+#           with:
+#               name: api-test-report---pr-${{ github.event.number }}
+#               path: artifacts/api
+
+#         - name: Download Playwright E2E test report artifact
+#           uses: actions/download-artifact@v3
+#           with:
+#               name: e2e-test-report---pr-${{ github.event.number }}
+#               path: artifacts/e2e
+
+#         - name: Prepare test summary
+#           id: prepare-test-summary
+#           uses: actions/github-script@v6
+#           env:
+#               API_SUMMARY_PATH: ${{ github.workspace }}/artifacts/api/allure-report/widgets/summary.json
+#               E2E_PW_SUMMARY_PATH: ${{ github.workspace }}/artifacts/e2e/allure-report/widgets/summary.json
+#               PR_NUMBER: ${{ github.event.number }}
+#               SHA: ${{ github.event.pull_request.head.sha }}
+#           with:
+#               result-encoding: string
+#               script: |
+#                   const script = require( './repo/.github/workflows/scripts/prepare-test-summary.js' )
+#                   return await script( { core } )
+
+#         - name: Find PR comment by github-actions[bot]
+#           uses: peter-evans/find-comment@034abe94d3191f9c89d870519735beae326f2bdb
+#           id: find-comment
+#           with:
+#               issue-number: ${{ github.event.pull_request.number }}
+#               comment-author: 'github-actions[bot]'
+#               body-includes: Test Results Summary
+
+#         - name: Create or update PR comment
+#           uses: peter-evans/create-or-update-comment@67dcc547d311b736a8e6c5c236542148a47adc3d
+#           with:
+#               comment-id: ${{ steps.find-comment.outputs.comment-id }}
+#               issue-number: ${{ github.event.pull_request.number }}
+#               body: ${{ steps.prepare-test-summary.outputs.result }}
+#               edit-mode: replace
+
+# publish-test-reports:
+#     name: Publish test reports
+#     if: |
+#         always() &&
+#         ! github.event.pull_request.head.repo.fork &&
+#         github.event.pull_request.user.login != 'github-actions[bot]' &&
+#         (
+#           contains( needs.*.result, 'success' ) ||
+#           contains( needs.*.result, 'failure' )
+#         )
+#     runs-on: ubuntu-20.04
+#     needs: [api-tests-run, e2e-tests-run, k6-tests-run]
+#     env:
+#         GITHUB_TOKEN: ${{ secrets.REPORTS_TOKEN }}
+#         PR_NUMBER: ${{ github.event.number }}
+#         RUN_ID: ${{ github.run_id }}
+#         COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
+#     steps:
+#         - name: Publish test reports
+#           env:
+#               API_ARTIFACT: api-test-report---pr-${{ github.event.number }}
+#               E2E_ARTIFACT: e2e-test-report---pr-${{ github.event.number }}
+#           run: |
+#               gh workflow run publish-test-reports-pr.yml \
+#                 -f run_id=$RUN_ID \
+#                 -f api_artifact=$API_ARTIFACT \
+#                 -f e2e_artifact=$E2E_ARTIFACT \
+#                 -f pr_number=$PR_NUMBER \
+#                 -f commit_sha=$COMMIT_SHA \
+#                 -f s3_root=public \
+#                 --repo woocommerce/woocommerce-test-reports
