Update workflow to use latest checkout actions

diff --git a/.github/workflows/pr-build-and-e2e-tests.yml b/.github/workflows/pr-build-and-e2e-tests.yml
--- a/.github/workflows/pr-build-and-e2e-tests.yml
+++ b/.github/workflows/pr-build-and-e2e-tests.yml
@@ -35,7 +35,7 @@ jobs:
         outputs:
             E2E_GRAND_TOTAL: ${{ steps.count_e2e_total.outputs.E2E_GRAND_TOTAL }}
         steps:
-            - uses: actions/checkout@v3
+            - uses: actions/checkout@v4
 
             - name: Setup WooCommerce Monorepo
               uses: ./.github/actions/setup-woocommerce-monorepo
@@ -87,12 +87,12 @@ jobs:
         if: ${{ always() }}
         steps:
             - run: |
-                result="${{ needs.e2e-tests-run.result }}"
-                if [[ $result != "success" && $result != "skipped" ]]; then
-                  echo "One or more e2e tests have failed!"
-                exit 1
-                fi
-                echo "e2e tests have completed successfully."
+                  result="${{ needs.e2e-tests-run.result }}"
+                  if [[ $result != "success" && $result != "skipped" ]]; then
+                    echo "One or more e2e tests have failed!"
+                  exit 1
+                  fi
+                  echo "e2e tests have completed successfully."
 
     merge-reports:
         name: Merge e2e test reports
@@ -105,7 +105,7 @@ jobs:
             ALLURE_RESULTS_DIR: ${{ github.workspace }}/plugins/woocommerce/tests/e2e-pw/test-results/allure-results
             ALLURE_REPORT_DIR: ${{ github.workspace }}/plugins/woocommerce/tests/e2e-pw/test-results/allure-report
         steps:
-            - uses: actions/checkout@v3
+            - uses: actions/checkout@v4
             - name: Setup WooCommerce Monorepo
               uses: ./.github/actions/setup-woocommerce-monorepo
               with:
@@ -140,14 +140,14 @@ jobs:
 
     api-tests-run:
         name: Runs API tests.
-        runs-on: ubuntu-20.04
+        runs-on: ubuntu-latest
         permissions:
             contents: read
         env:
             ALLURE_RESULTS_DIR: ${{ github.workspace }}/plugins/woocommerce/tests/api-core-tests/test-results/allure-results
             ALLURE_REPORT_DIR: ${{ github.workspace }}/plugins/woocommerce/tests/api-core-tests/test-results/allure-report
         steps:
-            - uses: actions/checkout@v3
+            - uses: actions/checkout@v4
 
             - name: Setup WooCommerce Monorepo
               uses: ./.github/actions/setup-woocommerce-monorepo
@@ -196,11 +196,11 @@ jobs:
     k6-tests-run:
         name: Runs k6 Performance tests
         if: github.event.pull_request.user.login != 'github-actions[bot]'
-        runs-on: ubuntu-20.04
+        runs-on: ubuntu-latest
         permissions:
             contents: read
         steps:
-            - uses: actions/checkout@v3
+            - uses: actions/checkout@v4
 
             - name: Setup WooCommerce Monorepo
               uses: ./.github/actions/setup-woocommerce-monorepo
@@ -234,7 +234,7 @@ jobs:
               contains( needs.*.result, 'success' ) ||
               contains( needs.*.result, 'failure' )
             )
-        runs-on: ubuntu-20.04
+        runs-on: ubuntu-latest
         needs: [api-tests-run, merge-reports]
         permissions:
             contents: read
@@ -251,7 +251,7 @@ jobs:
                   mkdir -p output
 
             - name: Checkout code
-              uses: actions/checkout@v3
+              uses: actions/checkout@v4
               with:
                   path: repo
 
@@ -307,7 +307,7 @@ jobs:
               contains( needs.*.result, 'success' ) ||
               contains( needs.*.result, 'failure' )
             )
-        runs-on: ubuntu-20.04
+        runs-on: ubuntu-latest
         needs: [api-tests-run, merge-reports, k6-tests-run]
         env:
             GITHUB_TOKEN: ${{ secrets.REPORTS_TOKEN }}
