Improve validation

diff --git a/.github/workflows/release-upload-to-wporg.yml b/.github/workflows/release-upload-to-wporg.yml
--- a/.github/workflows/release-upload-to-wporg.yml
+++ b/.github/workflows/release-upload-to-wporg.yml
@@ -77,9 +77,6 @@ jobs:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           GH_REPO: ${{ github.repository }}
         run: |
-          # Install SVN.
-          sudo apt-get -qq install -y subversion
-
           gh release download "$RELEASE_TAG" --pattern "woocommerce.zip" --output woocommerce.zip
 
           if [ ! -e "woocommerce.zip" ]; then
@@ -91,13 +88,23 @@ jobs:
           unzip -qq woocommerce.zip
 
           # Check that asset matches the release tag name.
+          if [ ! -e "woocommerce/woocommerce.php" ]; then
+            echo "::error::Asset in release tag '$RELEASE_TAG' is not a valid WooCommerce build."
+            exit 1
+          fi
+
+          # Check that version in ZIP matches tag.
           version_in_zip=$(cat woocommerce/woocommerce.php | grep -oP '(?<=Version: )(.+)' | head -n1)
           if [ "$version_in_zip" != "$RELEASE_TAG" ]; then
             echo "::error::Version in ZIP ($version_in_zip) does not match release number ($RELEASE_TAG)."
             exit 1
           fi
 
+          # Install SVN.
+          sudo apt-get -qq install -y subversion
+
           # Check that tag does not already exist on SVN repo.
+          # This might return a false negative due to connection errors, but the check is repeated later after checkout.
           if svn list "$SVN_URL/tags/$RELEASE_TAG" --username "$SVN_USERNAME" --password "$SVN_PASSWORD" > /dev/null 2>&1; then
             echo "::error::Tag '$RELEASE_TAG' already exists in SVN."
             exit 1
@@ -105,6 +112,10 @@ jobs:
 
           # Check whether this release should replace trunk in SVN.
           svn_plugin_version=$( svn cat "$SVN_URL/trunk/woocommerce.php" --username "$SVN_USERNAME" --password "$SVN_PASSWORD" |  grep -oP '(?<=Version: )(.+)' | head -n1 )
+          if [ -z "$svn_plugin_version" ]; then
+            echo "::error::Could not determine current version number in SVN."
+            exit 1
+          fi
 
           if php -r "die( version_compare( '$RELEASE_TAG', '$svn_plugin_version', '>' ) ? 0 : 1 );"; then
             echo "overwrite_trunk=1" >> "$GITHUB_OUTPUT"
