Add workflow to update changelog.txt after release

diff --git a/.github/workflows/release-new-release-published.yml b/.github/workflows/release-new-release-published.yml
--- a/.github/workflows/release-new-release-published.yml
+++ b/.github/workflows/release-new-release-published.yml
@@ -1,10 +1,11 @@
-name: 'Release: Notify in Slack when a new (pre)release is published'
+name: 'Release: Post-release published flows'
 on:
   release:
     types: [published]
 
 jobs:
   notify-release-published:
+    name: 'Notify in Slack when a new (pre)release is published'
     runs-on: ubuntu-latest
     if: ${{ !contains(github.event.release.tag_name, 'wc-beta-tester') }}
 
@@ -19,3 +20,62 @@ jobs:
             :woo-bounce: *<${{ github.event.release.html_url }}|WooCommerce ${{ github.event.release.name }}>* has been released! :rocket:
 
             (<!subteam^S086N376UTS> could you publish the release post? :ty2:)
+
+  update-global-changelog:
+    name: 'Update changelog.txt after any stable release'
+    runs-on: ubuntu-latest
+    if: ${{ ! contains( github.event.release.tag_name, 'wc-beta-tester' ) && ! contains( github.event.release.tag_name, '-rc' )  }}
+
+    steps:
+      - name: 'Fetch release readme.txt'
+        env:
+          RELEASE_TAG: ${{ github.event.release.tag_name }}
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          GH_REPO: ${{ github.repository }}
+        run: |
+          gh release download  --pattern 'woocommerce.zip'
+
+          if [[ ! -e "woocommerce.zip" ]]; then
+            echo "::error::Could not download asset for release '$RELEASE_TAG'."
+            exit 1
+          fi
+
+          unzip woocommerce.zip
+          if [[ ! -e woocommerce/readme.txt  ]]; then
+            echo "::error::Could not find readme.txt in asset for release '$RELEASE_TAG'."
+            exit 1
+          fi
+      - name: 'Fetch latest changelog.txt and changelog script'
+        uses: 'actions/checkout@v4'
+        with:
+          ref: trunk
+          sparse-checkout: |
+            /changelog.txt
+            /.github/workflows/scripts/release-readme-to-changelog.php
+          sparse-checkout-cone-mode: false
+          path: trunk
+      - name: 'Update changelog.txt'
+        run: |
+          php ./trunk/.github/workflows/scripts/release-readme-to-changelog.php ./woocommerce/readme.txt ./trunk/changelog.txt ./new-changelog.txt
+      - name: 'Push changes'
+        run: |
+          # Set up Git.
+          git config --global user.name 'WooCommerce Bot'
+          git config --global user.email 'no-reply@woocommerce.com'
+
+          # Push new changelog.txt.
+          cd trunk
+          git checkout -b "update-changelog-${{ github.event.release.tag_name }}"
+          mv ../new-changelog.txt changelog.txt
+          git commit -am 'Update changelog.txt after release ${{ github.event.release.tag_name }}'
+          git push origin "update-changelog-${{ github.event.release.tag_name }}"
+      - name: 'Open PR for changelog.txt updates'
+        env:
+          GH_TOKEN: ${{ github.token }}
+          GH_REPO: ${{ github.repository }}
+        run: |
+          gh pr create \
+            --title 'Update changelog.txt after ${{ github.event.release.tag_name }}' \
+            --body 'This PR updates the global changelog.txt file following the release of version ${{ github.event.release.tag_name }}.' \
+            --base trunk \
+            --head "update-changelog-${{ github.event.release.tag_name }}"
