Confirm stable tag while uploading a release to WordPress.org.

diff --git a/.github/workflows/release-upload-to-wporg.yml b/.github/workflows/release-upload-to-wporg.yml
--- a/.github/workflows/release-upload-to-wporg.yml
+++ b/.github/workflows/release-upload-to-wporg.yml
@@ -132,6 +132,15 @@ jobs:
           fi
 
           if php -r "die( version_compare( '$RELEASE_TAG', '$svn_plugin_version', '>' ) ? 0 : 1 );"; then
+            # Check that the stable tag in the release matches the stable tag in SVN.
+            svn_stable_version=$( svn cat "$SVN_URL/trunk/readme.txt" --username "$SVN_USERNAME" --password "$SVN_PASSWORD" |  grep -oP '(?<=Stable tag: )(.+)' | head -n1 )
+            stable_tag_in_release=$(cat woocommerce/readme.txt | grep -oP '(?<=Stable tag: )(.+)' | head -n1)
+
+            if [[ -z "$svn_stable_version" || $svn_stable_version != $stable_tag_in_release ]]; then
+              echo "::error::Stable tag in SVN ($svn_stable_version) does not match release stable tag ($stable_tag_in_release)."
+              exit 1
+            fi
+
             echo "overwrite_trunk=1" >> "$GITHUB_OUTPUT"
           else
             echo "overwrite_trunk=0" >> "$GITHUB_OUTPUT"
