Only verify naming when intending to create a GH release

diff --git a/.github/workflows/release-build-zip-file.yml b/.github/workflows/release-build-zip-file.yml
--- a/.github/workflows/release-build-zip-file.yml
+++ b/.github/workflows/release-build-zip-file.yml
@@ -84,7 +84,7 @@ jobs:
                   core.setOutput('runBuildZipJob', runBuildZipJob);
 
         - name: Notify Slack on failure
-          if: ${{ steps.verify-prs.outputs.failureMessage != '' }}
+          if: ${{ steps.verify-prs.outputs.failureMessage != '' && inputs.create_github_release }}
           uses: archive/github-actions-slack@f530f3aa696b2eef0e5aba82450e387bd7723903 #v2.0.0
           with:
               slack-bot-user-oauth-access-token: ${{ secrets.CODE_FREEZE_BOT_TOKEN }}
@@ -102,53 +102,44 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
-        if: ${{ ! inputs.skip_verify }}
+        with:
+          ref: ${{ inputs.branch || github.ref }}
+          path: checkout-branch
+        if: ${{ inputs.create_github_release && ! inputs.skip_verify }}
 
       - name: 'Pre-build verification'
-        if: ${{ ! inputs.skip_verify }}
+        if: ${{ inputs.create_github_release && ! inputs.skip_verify }}
+        env:
+          BRANCH: ${{ inputs.branch || github.ref }}
         run: |
-            branch_name="${GITHUB_REF#refs/heads/}"
+            # Branch name must be 'release/*'.
+            branch_name="${BRANCH#refs/heads/}"
             if  [[ $branch_name != release/* ]] ; then
-                echo "[ERR] Pre-build verification: the branch name is NOT matching 'release/*' pattern (identified as $branch_name)"
+                echo "::error::Pre-build verification: branch name '$branch_name' is not matching 'release/*' pattern."
                 exit 1
-            else
-                echo "[OK] Pre-build verification: the branch name is matching 'release/*' pattern ($branch_name)"
             fi
+
+            # Version number in branch name and plugin main version must match.
+            branch_plugin_version=$( cat checkout-branch/plugins/woocommerce/woocommerce.php | grep -oP '(?<=Version: )(.+)' | head -n1 )
             version_prefix=${branch_name/"release/"/""}
-
-            # Validate release version related attributions
-            branch_plugin_version=$( cat plugins/woocommerce/woocommerce.php | grep -oP '(?<=Version: )(.+)' | head -n1 )
-            svn_plugin_version=$( wget --quiet https://plugins.svn.wordpress.org/woocommerce/trunk/woocommerce.php -O /dev/stdout |  grep -oP '(?<=Version: )(.+)' | head -n1 )
             if [[ $branch_plugin_version != "$version_prefix."* ]] ; then
-                echo "[ERR] Pre-build verification: release version in branch is NOT matching '$version_prefix.*' pattern (identified as $branch_plugin_version)"
+                echo "::error::Pre-build verification: release version in branch ($branch_plugin_version) is not matching '$version_prefix.*' pattern."
                 exit 1
-            else
-                echo "[OK] Pre-build verification: release version in branch is matching '$version_prefix.*' pattern ($branch_plugin_version)"
-            fi
-            if [[ $branch_plugin_version == $svn_plugin_version ]] ; then
-                echo "[ERR] Pre-build verification: release version in branch is matching the one in SVN trunk (identified as $branch_plugin_version)"
-                exit 1
-            else
-                echo "[OK] Pre-build verification: release version in branch is NOT matching the one in SVN trunk ($branch_plugin_version vs $svn_plugin_version)"
             fi
 
-            # Validate stable version attribution
-            branch_stable_version=$( cat plugins/woocommerce/readme.txt | grep -oP '(?<=Stable tag: )(.+)' | head -n1 )
+            # Release should not already exist on wporg.
+            tag_exists=$(curl -s 'https://api.wordpress.org/plugins/info/1.2/?action=plugin_information&request\[slug\]=woocommerce' | jq "(.versions | has(\"$branch_plugin_version\"))")
+            if [ "$tag_exists" == "true" ]; then
+              echo "::error::Tag '$branch_plugin_version' already exists on WordPress.org."
+              exit 1
+            fi
+
+            # Stable version in release branch should match wporg.
             svn_stable_version=$( wget --quiet https://plugins.svn.wordpress.org/woocommerce/trunk/readme.txt -O /dev/stdout |  grep -oP '(?<=Stable tag: )(.+)' | head -n1 )
+            branch_stable_version=$( cat checkout-branch/plugins/woocommerce/readme.txt | grep -oP '(?<=Stable tag: )(.+)' | head -n1 )
             if [[ $branch_stable_version != $svn_stable_version ]] ; then
-                echo "[ERR] Pre-build verification: stable version in branch is NOT matching the one in SVN trunk (identified as $branch_stable_version)"
+                echo "::error::Pre-build verification: stable version in release branch ($branch_stable_version) is not matching the one in SVN trunk ($svn_stable_version)."
                 exit 1
-            else
-                echo "[OK] Pre-build verification: stable version in branch is matching the one in SVN trunk ($branch_stable_version vs $svn_stable_version)"
-            fi
-
-            # Validate changelog for the target release version
-            branch_changelog_version=$( cat changelog.txt | grep -oP '\d+\.\d+\.\d+ '| tail -n +1 | head -n1 )
-            if [[ $branch_plugin_version != *'-'* ]] && [[ $branch_plugin_version != $branch_changelog_version ]]; then
-                echo "[ERR] Pre-build verification: changelog for $branch_plugin_version is missing"
-                exit 1
-            else
-                echo "[OK] Pre-build verification: changelog for $branch_plugin_version is present or not required (the last entry is for $branch_changelog_version)"
             fi
 
   build:
@@ -225,7 +216,7 @@ jobs:
           release_name: ${{ steps.get_version.outputs.version }}
           draft: true
           prerelease: ${{ contains(steps.get_version.outputs.version, '-rc') }}
-          commitish: ${{ github.ref }}
+          commitish: ${{ inputs.branch || github.ref }}
           body: ''
 
       - name: Upload ZIP to release
