Require confirmation to run release-upload-to-wporg.

diff --git a/.github/workflows/release-upload-to-wporg.yml b/.github/workflows/release-upload-to-wporg.yml
--- a/.github/workflows/release-upload-to-wporg.yml
+++ b/.github/workflows/release-upload-to-wporg.yml
@@ -6,6 +6,11 @@ on:
         description: 'Release tag to upload (can be a draft release).'
         required: true
         default: ''
+      confirm-update:
+        description: 'I confirm that I want to upload a release to WordPress.org.'
+        type: boolean
+        required: true
+        default: false
 
 permissions: {}
 
@@ -20,6 +25,12 @@ jobs:
       release_asset: ${{ steps.fetch-release.outputs.release_asset }}
       overwrite_trunk: ${{ steps.check-asset.outputs.overwrite_trunk }}
     steps:
+      - name: Check confirmation
+        run: |
+          if [ "${{ github.event.inputs.confirm-update }}" != "true" ]; then
+            echo "::error::You must check the confirmation checkbox to proceed."
+            exit 1
+          fi
       - name: Fetch release
         id: fetch-release
         uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea #v7.0.1
